# Generated by Django 2.0 on 2017-12-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='tournament_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='packet_id',
        ),
        migrations.DeleteModel(
            name='Packet',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
