# Generated by Django 2.0 on 2018-08-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180813_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='packet_id',
            new_name='round_id',
        ),
    ]
