# Generated by Django 2.0 on 2018-08-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180813_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('round_number', models.IntegerField(
                    help_text='Corresponding round from which the packet comes')),
                ('type', models.CharField(help_text='Oneof PacketType values', max_length=20)),
                ('tournament_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='data.Tournament')),
            ],
        ),
        migrations.RemoveField(
            model_name='round',
            name='tournament_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='round_id',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.AddField(
            model_name='question',
            name='packet_id',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.CASCADE, to='data.Packet'),
            preserve_default=False,
        ),
    ]
