# Generated by Django 2.0 on 2018-08-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180814_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='type',
            new_name='packet_type',
        ),
    ]
