# Generated by Django 2.0 on 2018-08-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='packet_id',
            new_name='packet',
        ),
    ]
